### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by FoksVHox** [gabesystems/Pterodactyl-Themes#2]
Do these still works with the newest version of the panel?

**Comment by itsgabrieloliver** [comment]
>Do these still works with the newest version of the panel?

Hey sorry for the delayed response. I really haven't touched this in a decent amount of time. That said, I wouldn't recommend using these with newer versions as I haven't tested that and it may over-ride some important changes. I am planning on working on a bunch of cleaner and newer open-sourced themes that will work with newer versions.
